# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Lotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lotes.Lote')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Cliente')),
            ],
            options={
                'get_latest_by': 'order_date',
            },
        ),
    ]
