# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contratos.Contrato')),
            ],
        ),
    ]
