# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 02:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0004_auto_20170105_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
