# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0005_auto_20170105_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='NumeroOperacion',
            field=models.DecimalField(decimal_places=0, default='12345678', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='pagado',
            field=models.BooleanField(default='1'),
            preserve_default=False,
        ),
    ]
