# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratos', '0006_auto_20170105_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='costo',
            field=models.DecimalField(decimal_places=2, default='20000', max_digits=10),
            preserve_default=False,
        ),
    ]
