# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Etapa', models.CharField(max_length=12, verbose_name='Etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.PositiveIntegerField()),
                ('Area', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Area m2')),
                ('Etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lotes.Etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manzana', models.CharField(max_length=150, verbose_name='Nombre de la Manzana')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='Manzana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lotes.Manzana'),
        ),
    ]
