# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='Costo',
        ),
    ]
