# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.CharField(max_length=10)),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
